### ISSUE TITLE
Hangup issue when launching

### ISSUE THREAD

**Issue by jaredfox** [paul-io/momo-2#10]
I got the bot setup following the instructions on the wiki, but everytime i go to run the java -jar momo.2.0.6.jar it will get hung up and the bot never gets past anything but launching in discord.

**Comment by Flat** [comment]
Please attach the log from the bot. "It doesn't work" doesn't help anyone.

**Comment by jaredfox** [comment]
[main] INFO org.reflections.Reflections - Reflections took 635 ms to scan 1 urls, producing 11 keys and 172 values 
[main] INFO io.ph.bot.commands.CommandHandler - Initialized commands
[main] INFO io.ph.bot.Bot - Added API key for: maluser
[main] INFO io.ph.bot.Bot - Added API key for: malpass
[main] INFO io.ph.bot.Bot - Added API key for: twitch
[main] INFO io.ph.bot.Bot - Added API key for: youtube
[main] INFO io.ph.bot.Bot - Added API key for: battlenet
[main] INFO io.ph.bot.Bot - Added API key for: saucenao
[main] INFO io.ph.bot.Bot - Added API key for: redditusername
[main] INFO io.ph.bot.Bot - Added API key for: redditpassword
[main] INFO io.ph.bot.Bot - Added API key for: redditkey
[main] INFO io.ph.bot.Bot - Added API key for: redditsecret
[main] INFO io.ph.bot.Bot - Added API key for: twitterappkey
[main] INFO io.ph.bot.Bot - Added API key for: twitterappsecret
[main] INFO io.ph.bot.Bot - Added API key for: twittertokenkey
[main] INFO io.ph.bot.Bot - Added API key for: twittertokensecret
[14:23:09] [Info] [JDA]: Login Successful!
[14:23:10] [Info] [JDASocket]: Connected to WebSocket
[14:23:10] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel. JSON: {"permission_overwrites":[{"allow":37215297,"deny":834674704,"id":"267384547296018432","type":"role"},{"allow":871890001,"deny":0,"id":"271818167649697793","type":"role"},{"allow":871890001,"deny":0,"id":"272580698123272192","type":"role"},{"allow":603454529,"deny":268435472,"id":"271819448216846337","type":"role"}],"name":"Gaming Channels","bitrate":64000,"position":2,"id":"362793000893546497","user_limit":0,"type":4}
[14:23:10] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel. JSON: {"permission_overwrites":[{"allow":35980352,"deny":835909649,"id":"267384547296018432","type":"role"},{"allow":871890001,"deny":0,"id":"271818167649697793","type":"role"},{"allow":66575424,"deny":805314577,"id":"271821988253663235","type":"role"},{"allow":871890001,"deny":0,"id":"272580698123272192","type":"role"},{"allow":603454528,"deny":268435473,"id":"271819448216846337","type":"role"}],"name":"Streamers","bitrate":64000,"position":3,"id":"360787534634024971","user_limit":0,"type":4}
[14:23:10] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel. JSON: {"permission_overwrites":[{"allow":37215297,"deny":834674704,"id":"267384547296018432","type":"role"},{"allow":871890001,"deny":0,"id":"271818167649697793","type":"role"},{"allow":871890001,"deny":0,"id":"272580698123272192","type":"role"},{"allow":603454529,"deny":268435472,"id":"271819448216846337","type":"role"}],"name":"Public Chat","bitrate":64000,"position":0,"id":"360786557793468426","user_limit":0,"type":4}
[14:23:10] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel. JSON: {"permission_overwrites":[{"allow":35651584,"deny":836238417,"id":"267384547296018432","type":"role"},{"allow":871890001,"deny":0,"id":"271818167649697793","type":"role"},{"allow":871890001,"deny":0,"id":"272580698123272192","type":"role"},{"allow":603454528,"deny":268435473,"id":"271819448216846337","type":"role"}],"name":"Private Channels","bitrate":64000,"position":4,"id":"360787716126015489","user_limit":0,"type":4}
[14:23:10] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel. JSON: {"permission_overwrites":[{"allow":37215297,"deny":834674704,"id":"267384547296018432","type":"role"},{"allow":871890001,"deny":0,"id":"271818167649697793","type":"role"},{"allow":871890001,"deny":0,"id":"272580698123272192","type":"role"},{"allow":603454529,"deny":268435472,"id":"271819448216846337","type":"role"}],"name":"Public Voice Channels","bitrate":64000,"position":1,"id":"360787161592758272","user_limit":0,"type":4}
[14:23:10] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel (ChannelPass). JSON: {"permission_overwrites":[{"allow":37215297,"deny":834674704,"id":"267384547296018432","type":"role"},{"allow":871890001,"deny":0,"id":"271818167649697793","type":"role"},{"allow":871890001,"deny":0,"id":"272580698123272192","type":"role"},{"allow":603454529,"deny":268435472,"id":"271819448216846337","type":"role"}],"name":"Gaming Channels","bitrate":64000,"position":2,"id":"362793000893546497","user_limit":0,"type":4}
[14:23:10] [Fatal] [JDASocket]: Encountered an exception:
[14:23:11] [Fatal] [JDASocket]: java.lang.RuntimeException: Got permission_override for unknown channel with id: 362793000893546497
	at net.dv8tion.jda.core.entities.EntityBuilder.createGuildChannelPass(EntityBuilder.java:394)
	at net.dv8tion.jda.core.entities.EntityBuilder.createGuildFirstPass(EntityBuilder.java:281)
	at net.dv8tion.jda.core.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:39)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:38)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:770)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:500)
	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:803)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

This is where is stops. I double checked the APIs and the token IDs and cant figure out if its one of those causing it to hang up.

**Comment by NostalgiaNinja** [comment]
Hi.

You'll need the latest 2.1.0beta release which adds channel category support for Momo.  everything else seems to be set up fine.

**Comment by jaredfox** [comment]
Thanks, was able to get it up and running with that!
