### ISSUE TITLE
Exception in thread "main", Parameter 'directory" is not a directory: resources/guilds

### ISSUE THREAD

**Issue by iViscosity** [paul-io/momo-2#2]
Hey! Sorry if this seems really obvious to you, but I've never used SSH or a VPS or anything like this before, so please bare with me. I followed all of the instructions to setting this up (installing maven, cloning the repo, setting up a bot account [that I already had]) and so on and so forth, but when I got to actually running the bot (java -jar momo-2.1.0beta.jar was the command I ran), I got this error:

```
    Exception in thread "main" java.lang.IllegalArgumentException: Parameter 'directory' is not a directory: 
    resources/guilds
        at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:536)
        at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:512)
        at io.ph.bot.commands.CommandHandler.normalizeCommands(CommandHandler.java:123)
        at io.ph.bot.commands.CommandHandler.initCommands(CommandHandler.java:72)
        at io.ph.bot.Launcher.main(Launcher.java:17)
```

and I'm not quite sure what that means. Can you help point me in the right direction?

**Comment by iViscosity** [comment]
Nevermind, it was a mistake on my end. I forgot to move the files from "momo-2/resources" to "momo-2/target/resources". It works now :)

**Comment by paul-io** [comment]
Make sure to read the fine print about `make clean install` then! `clean` removes every file inside that `/target/` directory, so you may want to move the .jar to a different directory (maybe one directory up to use the original `momo-2/resources` folder?)

**Comment by iViscosity** [comment]
See I did read that, I just didn't know I had to do it in the first place :P Like I said I'm kinda slow.

**Comment by paul-io** [comment]
No problems haha, just wanted to make sure you don't accidentally wipe your files

**Comment by iViscosity** [comment]
Sorry, I know this is off-topic and not a good place to put this because it's under Issues, but I have a question. Do you know how I could get this bot to run using node.js?

**Comment by paul-io** [comment]
Node.js is pretty much completely unrelated to the Java ecosystem

And yeah, there's an easy way using the program `screen`. Basically, connect to your server and type in `screen`. This brings up a "virtual" terminal, so run the bot there. Then, to "disconnect" from this screen, you input `CTRL + A, D`. You're safe to close your connection window

Then, to get back into it, type in `screen -ls`. This lists out each screen terminal you have. Then, you can type in `screen -r ####` where #### is the ID of the screen that comes out. 

If you only have one `screen` open, you can just type in `screen -r` without having to do the `-ls` step

**Comment by paul-io** [comment]
A better place to discuss would be in my discord server: https://discord.gg/uM3pyW8
